apiVersion: v1
kind: Service
metadata:
  name: {{ include "helloworld.fullname" . }}
  labels:
{{ include "helloworld.labels.standard" . | indent 4 }}
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ template "helloworld.name" . }}
    release: {{ .Release.Name | quote }}
